### ISSUE TITLE
Question in object instantiating

### ISSUE THREAD

**Issue by andrewg78** [rockswang/java-curl#1]
I have a url and parameters in a single string.
How can I instantiate Curl object from that string?
Is it even possible ?
Something like CUrl curl = new CUrl("http://<ip>/<page> --location");

**Comment by rockswang** [comment]
you can split command line to String[] and then pass them to opt() method.
e.g.:
CUrl curl = new CUrl().opt("http://xxx/x -L".split("\\s+"));
