### ISSUE TITLE
How I can get response output?

### ISSUE THREAD

**Issue by BaxAndrei** [rockswang/java-curl#20]
Hi. How I can get response output from curl request?

```
			CUrl curl = new CUrl("https://www.baxandrei.ro/");
			curl.exec();
			System.out.println(curl.output("body").toString());
```

After request, code sould get back an key to use.

**Comment by BaxAndrei** [comment]
I found this comment https://github.com/rockswang/java-curl/issues/8#issuecomment-554171395. After I added this to curl.exec `curl.exec(CUrl.UTF8, null)` is working. TY!

**Comment by rockswang** [comment]
you can use output method, e.g.:
```java
CUrl.MemIO out = new CUrl.MemIO();
new CUrl(url).output(out).exec();
String body = new String(out.toByteArray());
```
