### ISSUE TITLE
the function header() can not delete the header args which i specified

### ISSUE THREAD

**Issue by bennyhl2019** [rockswang/java-curl#3]
my coding like this:
CUrl curl = new CUrl("http://www.baidu.com/api/v1/upimg").header("User-Agent:").header("Pragma:");

but when i wireshark the cap ,the header like this
POST /api/v1/upimg HTTP/1.1
Accept: */*
User-Agent: 
Pragma: 
Content-Length: 406
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Host: www.baidu.com
Connection: keep-alive

**Comment by rockswang** [comment]
thank you for reporting, I have fixed this in my local, however, since 'Progma', 'User-Agent' etc. are special headers, the java low-level http framework will add them anyway
