### ISSUE TITLE
When using put, data is invalid.

### ISSUE THREAD

**Issue by cower** [rockswang/java-curl#4]
Curl curl2 = new Curl("https://api.name.com/v4/domains/"+ name.getDomainName() +"/records/" + name.getId()).header("Accept:application/json").proxy("127.0.0.1", 8888) .insecure().opt("-X","PUT").opt("--user","aa:bb").data(putjson.toJSONString()) ; 
              
fiddler:
curl -k -i --raw -o 0.dat -X PUT "https://api.name.com/v4/domains/aa.com/records/1026317707" -H "Accept: application/json" -H "User-Agent: Java-Curl version 1.2.2 by Rocks Wang(https://github.com/rockswang)" -H "Authorization: Basic " -H "Cache-Control: no-cache" -H "Pragma: no-cache" -H "Host: api.name.com" -H "Connection: keep-alive" -H "Cookie: REG_IDT=v9n5uphaenjn09h0bj0d6tqsn2"

**Comment by rockswang** [comment]
please find line contains:
```if ("POST".equals(method)) {```
then modify it to:
```if ("POST".equals(method) || "PUT".equals(method)) {```

If this resolves your problem please let me know, I'll merge it to master

**Comment by cower** [comment]
yes, I solved this, but I have not tried other, is there a problem? thank you!
