### ISSUE TITLE
Cookie保存到文件，在读取Cookie进行请求访问时返回302

### ISSUE THREAD

**Issue by shaozhipeng** [rockswang/java-curl#5]
`
// cookie保存到文件里
CUrl.IO cookieJar = new CUrl.FileIO(new File("").getAbsolutePath() + "/cookieJar");

// 登录的时候存
CUrl curl = new CUrl(QUERY_AUTHENTICATION_URL)
                .headers(headers)
                // 把cookie写入cookieJar
                .cookieJar(cookieJar);

        curl.exec();

        return curl.getHttpCode() + "";

// 查询的时候读取cookie
CUrl curl = new CUrl(QUERY_URL)
                .data(data)
                .header("Content-Type:application/json")
                // 使用cookie 下同
                .cookie(cookieJar);

        curl.exec();
        return curl.getStdout(jsonResolver, null);

// 返回httpCode为302 重定向
@Override
        public String resolve(int httpCode, byte[] responseBody) throws Throwable {
            System.out.println("httpCode:" + httpCode);
            return new String(responseBody, "UTF-8");
        }
`
cookie的内容类似：
127.0.0.1	FALSE	/kylin	FALSE	2147483647	JSESSIONID	824A2C3AFBBACE36837E4AE69B0C2D9E

经验证，使用new CUrl.CookieIO();是可以的。

**Comment by rockswang** [comment]
java-curl默认会维持每条线程内的cookie，因此通常不需要自行处理cookieJar，除非：
* 调试过程中需要查看本地保存了哪些cookie
* 需要修改cookie值，这种情况可以用CookieIO
* 和其它系统集成，比如从浏览器获取cookie，或者提供cookie供浏览器使用
