### ISSUE TITLE
How to download jpg file from Instagram?

### ISSUE THREAD

**Issue by udexon** [rockswang/java-curl#6]
Instagram publishes a photo using "shortcode", e.g. B4c2PBVAmWX

https://www.instagram.com/p/B4c2PBVAmWX/

First, I downloaded the html file using the URL above using java-curl. I inspected the <meta> tag to obtain the url for the jpg file:

https://instagram.fkul4-2.fna.fbcdn.net/vp/34854b7e925181670c1e2cadb1de9872/5E42DA32/t51.2885-15/e35/p1080x1080/72703005_418674925489247_2184660954511026364_n.jpg?_nc_ht=instagram.fkul4-2.fna.fbcdn.net&_nc_cat=111/

When I used java-curl to download the jpg file using the second URL, the saved file is corrupted.

It works perfectly with PHP copy().

So I am wondering what kind of options or variables I need to set to make it work?

Thanks a lot for the help.

I think your project is really great. Thanks a lot for sharing with us.

**Comment by rockswang** [comment]
I can download the image successfully on command-line: 
```java -jar java-curl-1.2.2.2.jar "https://scontent-sin6-2.cdninstagram.com/vp/99d8eadadca59bb4a2833d0ab9ad342b/5E42DA32/t51.2885-15/e35/p1080x1080/72703005_418674925489247_2184660954511026364_n.jpg?_nc_ht=scontent-sin6-2.cdninstagram.com&_nc_cat=111"  --output d:\tmp\inst_a.jpg```
In java code I think you can also use `output` method with a MemIO object to download the image into a memory buffer.

**Comment by udexon** [comment]
Thanks a lot for the quick response.

Can you show me sample Java code on how to add the options?

I tried various ways but none of that worked.

e.g. 
```
        /*   // Test code
        String[] s_args = new String[2];
        s_args[0] = ( url );
        s_args[1] = "-o";
        */
        String[] s_args = { url };
        System.out.println( "  403 curl_copy "+ s_args[0] );
	String s = new CUrl().opt(s_args).exec(null);
```

How to specify the output filename in `opt()` ?

**Comment by udexon** [comment]
Problem solved:

```
String[] s_args = { url, "--output", "test.jpg" };
String s = new CUrl().opt(s_args).exec(null);
```

Thanks a lot for the help!!

**Comment by rockswang** [comment]
Congratulation! 
You can also use following code to download image into memory:
```java
byte[] imgData = new CUrl(imgUrl).exec(CUrl.RAW, null);
```
